// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4iUb9F3Aq2j7-9w5y4845AMrhRnwdK4',
    appId: '1:531974328621:web:87d04cb4d61878dfd183a4',
    messagingSenderId: '531974328621',
    projectId: 'happy-cherry',
    authDomain: 'happy-cherry.firebaseapp.com',
    storageBucket: 'happy-cherry.firebasestorage.app',
    measurementId: 'G-QYMK3G6KTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFsA6qyOkzvFgqbcEfw2TrtYWD_ljjRF4',
    appId: '1:531974328621:android:f5c9694605a086d0d183a4',
    messagingSenderId: '531974328621',
    projectId: 'happy-cherry',
    storageBucket: 'happy-cherry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD61elxztcikB5MyEImVAgD3E8yoIxi6cE',
    appId: '1:531974328621:ios:75e24a86083f784fd183a4',
    messagingSenderId: '531974328621',
    projectId: 'happy-cherry',
    storageBucket: 'happy-cherry.firebasestorage.app',
    iosBundleId: 'com.example.happyCherry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD61elxztcikB5MyEImVAgD3E8yoIxi6cE',
    appId: '1:531974328621:ios:75e24a86083f784fd183a4',
    messagingSenderId: '531974328621',
    projectId: 'happy-cherry',
    storageBucket: 'happy-cherry.firebasestorage.app',
    iosBundleId: 'com.example.happyCherry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw4iUb9F3Aq2j7-9w5y4845AMrhRnwdK4',
    appId: '1:531974328621:web:87d04cb4d61878dfd183a4',
    messagingSenderId: '531974328621',
    projectId: 'happy-cherry',
    authDomain: 'happy-cherry.firebaseapp.com',
    storageBucket: 'happy-cherry.firebasestorage.app',
    measurementId: 'G-QYMK3G6KTK',
  );
}
